[package]
name = "open-telemetry-exporter"
version = "0.1.0"
edition = "2024"

[features]
default = ["reqwest-blocking"]
reqwest-blocking = ["opentelemetry-otlp/reqwest-blocking-client"]

[dependencies]
opentelemetry = { version = "0.31.0", features = ["logs", "metrics"] }
opentelemetry_sdk = { version = "0.31.0", features = ["logs", "metrics"] }
opentelemetry-otlp = { version = "0.31.0", features = ["http-proto", "logs", "metrics", "reqwest-blocking-client"] }
opentelemetry-log = "0.2.0"
reqwest = { version = "0.12.24", features = ["json"] }
tokio = { version = "1", features = ["rt", "macros", "time"] }
sysinfo = "0.37.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9"
windows-service = "0.8.0"
glob = "0.3.2"

[dev-dependencies]
tempfile = "3.0"
